import express from 'express';
import cors from 'cors';
import nodemailer from 'nodemailer';
import dotenv from 'dotenv';
import Stripe from 'stripe';
import Razorpay from 'razorpay';
import crypto from 'crypto';

dotenv.config();

const app = express();
const port = process.env.PORT || 5001;

// Middlewares
app.use(cors({
  origin: '*', // Adjust to specific frontend URL in production, e.g. http://localhost:5173
  methods: ['GET', 'POST'],
  allowedHeaders: ['Content-Type']
}));
app.use(express.json());

// Verify email configuration on startup
const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER || 'kjaydeep842@gmail.com',
    pass: process.env.EMAIL_PASS || 'frqi tcpu mvuq pyhe'
  }
});

transporter.verify((error, success) => {
  if (error) {
    console.error('Error configuring email transporter:', error);
  } else {
    console.log('Server is ready to send emails!');
  }
});

// API endpoint for inquiry
app.post('/api/contact', async (req, res) => {
  const { name, email, message } = req.body;

  if (!name || !email || !message) {
    return res.status(400).json({ error: 'All fields (name, email, message) are required.' });
  }

  const ownerEmail = process.env.EMAIL_USER || 'kjaydeep842@gmail.com';

  // 1. Email template for Owner (Inquiry Alert)
  const ownerMailOptions = {
    from: `"Portfolio System" <${ownerEmail}>`,
    to: ownerEmail,
    subject: `🚀 New Portfolio Inquiry from ${name}`,
    html: `
      <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #0f172a; color: #f8fafc;">
        <div style="border-bottom: 2px solid #10b981; padding-bottom: 15px; margin-bottom: 20px; display: flex; align-items: center; justify-content: space-between;">
          <h2 style="margin: 0; color: #10b981; font-size: 20px; letter-spacing: 0.5px;">SYSTEM TELEMETRY: NEW INQUIRY</h2>
        </div>
        
        <div style="background-color: #1e293b; padding: 15px; border-radius: 8px; margin-bottom: 20px; border: 1px solid #334155;">
          <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
            <tr>
              <td style="padding: 6px 0; color: #94a3b8; width: 120px; font-weight: bold;">Sender Name:</td>
              <td style="padding: 6px 0; color: #ffffff; font-weight: 500;">${name}</td>
            </tr>
            <tr>
              <td style="padding: 6px 0; color: #94a3b8; font-weight: bold;">Sender Email:</td>
              <td style="padding: 6px 0;"><a href="mailto:${email}" style="color: #38bdf8; text-decoration: none; font-weight: 500;">${email}</a></td>
            </tr>
            <tr>
              <td style="padding: 6px 0; color: #94a3b8; font-weight: bold;">Timestamp:</td>
              <td style="padding: 6px 0; color: #cbd5e1; font-family: monospace;">${new Date().toLocaleString()}</td>
            </tr>
          </table>
        </div>

        <div style="background-color: #1e293b; padding: 20px; border-radius: 8px; border-left: 4px solid #10b981; margin-bottom: 20px;">
          <h3 style="margin-top: 0; margin-bottom: 10px; color: #38bdf8; font-size: 14px; text-transform: uppercase; letter-spacing: 0.5px;">Inquiry Message:</h3>
          <p style="margin: 0; color: #e2e8f0; font-size: 14px; line-height: 1.6; white-space: pre-wrap;">${message}</p>
        </div>

        <div style="text-align: center; border-top: 1px solid #334155; padding-top: 15px; margin-top: 25px;">
          <p style="margin: 0; font-size: 11px; color: #64748b; font-family: monospace;">
            This email was auto-generated by your portfolio application backend.
          </p>
        </div>
      </div>
    `
  };

  // 2. Email template for User (Auto-response Thank You)
  const userMailOptions = {
    from: `"Jaydeep Khunt" <${ownerEmail}>`,
    to: email,
    subject: `Thank you for reaching out, ${name}!`,
    html: `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 30px 20px; border: 1px solid #e2e8f0; border-radius: 16px; background-color: #ffffff; color: #334155; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03);">
        <div style="text-align: center; margin-bottom: 30px;">
          <div style="display: inline-block; width: 60px; height: 60px; border-radius: 50%; background-color: #ecfdf5; border: 1px solid #a7f3d0; text-align: center; line-height: 60px; margin-bottom: 15px;">
            <span style="font-size: 28px; vertical-align: middle;">✉️</span>
          </div>
          <h2 style="margin: 0; color: #0f172a; font-size: 22px; font-weight: 850;">Thank You for Reaching Out!</h2>
          <p style="margin: 5px 0 0 0; color: #64748b; font-size: 14px;">Inquiry Confirmation</p>
        </div>

        <div style="line-height: 1.6; font-size: 15px; color: #475569; margin-bottom: 25px;">
          <p>Hi <strong>${name}</strong>,</p>
          
          <p>
            Thank you for visiting my portfolio website and initiating contact. I have successfully received your message and wanted to confirm that your inquiry is in my queue.
          </p>
          
          <p style="background-color: #f8fafc; border-left: 3px solid #10b981; padding: 12px 16px; margin: 20px 0; border-radius: 0 8px 8px 0; font-style: italic; color: #334155;">
            "Thanks for contacting us! I will connect with you soon to discuss your requirements in detail."
          </p>
          
          <p>
            If you need immediate assistance or want to share additional details, feel free to reply directly to this email.
          </p>
        </div>

        <div style="border-top: 1px solid #f1f5f9; padding-top: 25px; margin-top: 30px;">
          <table style="width: 100%;">
            <tr>
              <td>
                <p style="margin: 0; font-weight: bold; color: #0f172a; font-size: 15px;">Jaydeep Khunt</p>
                <p style="margin: 2px 0 0 0; color: #64748b; font-size: 13px;">Full Stack Engineer & Systems Architect</p>
              </td>
              <td style="text-align: right;">
                <a href="https://linkedin.com/in/jaydeep-khunt" style="display: inline-block; margin-left: 10px; color: #0077b5; text-decoration: none; font-size: 13px; font-weight: 600;">LinkedIn</a>
                <a href="https://github.com/kjaydeep842" style="display: inline-block; margin-left: 10px; color: #0f172a; text-decoration: none; font-size: 13px; font-weight: 600;">GitHub</a>
              </td>
            </tr>
          </table>
        </div>
      </div>
    `
  };

  try {
    // Send email to owner
    await transporter.sendMail(ownerMailOptions);
    console.log(`Notification email sent to owner (${ownerEmail}) successfully.`);

    // Send thank you email to user
    await transporter.sendMail(userMailOptions);
    console.log(`Auto-response thank you email sent to user (${email}) successfully.`);

    return res.status(200).json({ success: true, message: 'Emails sent successfully.' });
  } catch (error) {
    console.error('Failed to send email:', error);
    return res.status(500).json({ error: 'Internal server error while sending emails.' });
  }
});

// Initialize SDKs dynamically based on env keys
const getStripe = () => {
  if (process.env.STRIPE_SECRET_KEY) {
    return new Stripe(process.env.STRIPE_SECRET_KEY);
  }
  return null;
};

const getRazorpay = () => {
  if (process.env.RAZORPAY_KEY_ID && process.env.RAZORPAY_KEY_SECRET) {
    return new Razorpay({
      key_id: process.env.RAZORPAY_KEY_ID,
      key_secret: process.env.RAZORPAY_KEY_SECRET
    });
  }
  return null;
};

// Stripe Session creation
app.post('/api/payments/create-stripe-session', async (req, res) => {
  const { planName, amount, customerEmail } = req.body;
  const stripe = getStripe();
  const origin = req.headers.origin || 'http://localhost:5173';

  console.log(`Creating Stripe Checkout Session for ${planName} (${amount} USD)...`);

  if (stripe) {
    try {
      const session = await stripe.checkout.sessions.create({
        payment_method_types: ['card'],
        line_items: [
          {
            price_data: {
              currency: 'usd',
              product_data: {
                name: planName,
                description: `Purchase of ${planName}`,
              },
              unit_amount: Math.round(amount * 100), // in cents
            },
            quantity: 1,
          },
        ],
        mode: 'payment',
        customer_email: customerEmail,
        success_url: `${origin}/?payment=success&gateway=stripe&session_id={CHECKOUT_SESSION_ID}&plan=${encodeURIComponent(planName)}&amount=${amount}`,
        cancel_url: `${origin}/?payment=cancel&gateway=stripe`,
      });
      res.json({ url: session.url, simulated: false });
    } catch (error) {
      console.error('Stripe error:', error);
      res.status(500).json({ error: error.message });
    }
  } else {
    // Simulated Mode
    const mockSessionId = 'cs_test_' + Math.random().toString(36).substring(7);
    const simulatedUrl = `${origin}/?payment=success&gateway=stripe&session_id=${mockSessionId}&plan=${encodeURIComponent(planName)}&amount=${amount}&mode=simulation`;
    res.json({ url: simulatedUrl, simulated: true });
  }
});

// Razorpay Order creation
app.post('/api/payments/create-razorpay-order', async (req, res) => {
  const { planName, amount } = req.body;
  const razorpay = getRazorpay();

  console.log(`Creating Razorpay Order for ${planName} (${amount} INR)...`);

  const amountInPaise = Math.round(amount * 100);

  if (razorpay) {
    try {
      const options = {
        amount: amountInPaise,
        currency: 'INR',
        receipt: 'receipt_order_' + Math.random().toString(36).substring(7),
      };
      const order = await razorpay.orders.create(options);
      res.json({
        orderId: order.id,
        key: process.env.RAZORPAY_KEY_ID,
        amount: order.amount,
        currency: order.currency,
        simulated: false
      });
    } catch (error) {
      console.error('Razorpay error:', error);
      res.status(500).json({ error: error.message });
    }
  } else {
    // Simulated Mode
    res.json({
      orderId: 'rzp_order_sim_' + Math.random().toString(36).substring(7),
      key: 'rzp_test_simulated_key',
      amount: amountInPaise,
      currency: 'INR',
      simulated: true
    });
  }
});

// PayPal Order creation
app.post('/api/payments/create-paypal-order', async (req, res) => {
  const { planName, amount } = req.body;
  const origin = req.headers.origin || 'http://localhost:5173';

  console.log(`Creating PayPal Order for ${planName} (${amount} USD)...`);

  const clientId = process.env.PAYPAL_CLIENT_ID;
  const clientSecret = process.env.PAYPAL_CLIENT_SECRET;

  if (clientId && clientSecret) {
    try {
      // Get Access Token
      const auth = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');
      const tokenResponse = await fetch('https://api-m.sandbox.paypal.com/v1/oauth2/token', {
        method: 'POST',
        headers: {
          'Authorization': `Basic ${auth}`,
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'grant_type=client_credentials',
      });
      const tokenData = await tokenResponse.json();
      const accessToken = tokenData.access_token;

      // Create Order
      const orderResponse = await fetch('https://api-m.sandbox.paypal.com/v2/checkout/orders', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          intent: 'CAPTURE',
          purchase_units: [
            {
              amount: {
                currency_code: 'USD',
                value: amount.toFixed(2),
              },
              description: planName,
            },
          ],
          application_context: {
            brand_name: 'Jaydeep Khunt Portfolio',
            landing_page: 'NO_PREFERENCE',
            user_action: 'PAY_NOW',
            return_url: `${origin}/?payment=success&gateway=paypal&plan=${encodeURIComponent(planName)}&amount=${amount}`,
            cancel_url: `${origin}/?payment=cancel&gateway=paypal`,
          },
        }),
      });

      const orderData = await orderResponse.json();
      const approvalUrl = orderData.links.find((link) => link.rel === 'approve')?.href;

      res.json({ url: approvalUrl, orderId: orderData.id, simulated: false });
    } catch (error) {
      console.error('PayPal error:', error);
      res.status(500).json({ error: error.message });
    }
  } else {
    // Simulated Mode
    const simulatedUrl = `${origin}/?payment=success&gateway=paypal&order_id=pay_sim_${Math.random().toString(36).substring(7)}&plan=${encodeURIComponent(planName)}&amount=${amount}&mode=simulation`;
    res.json({ url: simulatedUrl, simulated: true });
  }
});

// Cashfree Order creation
app.post('/api/payments/create-cashfree-order', async (req, res) => {
  const { planName, amount, customerEmail, customerName, customerPhone } = req.body;
  const origin = req.headers.origin || 'http://localhost:5173';

  console.log(`Creating Cashfree Order for ${planName} (${amount} INR)...`);

  const appId = process.env.CASHFREE_APP_ID;
  const secretKey = process.env.CASHFREE_SECRET_KEY;

  if (appId && secretKey) {
    try {
      const orderId = 'order_' + Math.random().toString(36).substring(7);
      const response = await fetch('https://sandbox.cashfree.com/pg/orders', {
        method: 'POST',
        headers: {
          'x-api-version': '2023-08-01',
          'x-client-id': appId,
          'x-client-secret': secretKey,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          order_id: orderId,
          order_amount: parseFloat(amount).toFixed(2),
          order_currency: 'INR',
          customer_details: {
            customer_id: 'cust_' + Math.random().toString(36).substring(7),
            customer_email: customerEmail || 'test@gmail.com',
            customer_phone: customerPhone || '9999999999',
            customer_name: customerName || 'Test User'
          },
          order_meta: {
            return_url: `${origin}/?payment=success&gateway=cashfree&order_id=${orderId}&plan=${encodeURIComponent(planName)}&amount=${amount}`
          }
        }),
      });

      const orderData = await response.json();
      res.json({
        paymentSessionId: orderData.payment_session_id,
        orderId: orderData.order_id,
        simulated: false
      });
    } catch (error) {
      console.error('Cashfree error:', error);
      res.status(500).json({ error: error.message });
    }
  } else {
    // Simulated Mode
    res.json({
      paymentSessionId: 'cf_session_sim_' + Math.random().toString(36).substring(7),
      orderId: 'cf_order_sim_' + Math.random().toString(36).substring(7),
      simulated: true
    });
  }
});

// Verification Endpoint
app.post('/api/payments/verify-payment', async (req, res) => {
  const { gateway, orderId, paymentId, signature, simulated } = req.body;
  console.log(`Verifying payment for ${gateway}...`);

  if (simulated) {
    return res.json({ success: true, verified: true, simulated: true });
  }

  try {
    if (gateway === 'stripe') {
      const stripe = getStripe();
      if (!stripe) throw new Error('Stripe not configured');
      const session = await stripe.checkout.sessions.retrieve(paymentId);
      if (session.payment_status === 'paid') {
        return res.json({ success: true, verified: true });
      }
    } else if (gateway === 'razorpay') {
      const secret = process.env.RAZORPAY_KEY_SECRET;
      if (!secret) throw new Error('Razorpay secret not configured');
      const generated_signature = crypto
        .createHmac('sha256', secret)
        .update(orderId + "|" + paymentId)
        .digest('hex');
      if (generated_signature === signature) {
        return res.json({ success: true, verified: true });
      }
    } else if (gateway === 'cashfree') {
      const appId = process.env.CASHFREE_APP_ID;
      const secretKey = process.env.CASHFREE_SECRET_KEY;
      if (!appId || !secretKey) throw new Error('Cashfree not configured');
      const response = await fetch(`https://sandbox.cashfree.com/pg/orders/${orderId}`, {
        headers: {
          'x-api-version': '2023-08-01',
          'x-client-id': appId,
          'x-client-secret': secretKey,
        }
      });
      const orderData = await response.json();
      if (orderData.order_status === 'PAID') {
        return res.json({ success: true, verified: true });
      }
    } else if (gateway === 'paypal') {
      const clientId = process.env.PAYPAL_CLIENT_ID;
      const clientSecret = process.env.PAYPAL_CLIENT_SECRET;
      if (!clientId || !clientSecret) throw new Error('PayPal not configured');
      
      const auth = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');
      const tokenResponse = await fetch('https://api-m.sandbox.paypal.com/v1/oauth2/token', {
        method: 'POST',
        headers: {
          'Authorization': `Basic ${auth}`,
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: 'grant_type=client_credentials',
      });
      const tokenData = await tokenResponse.json();
      const accessToken = tokenData.access_token;

      const captureResponse = await fetch(`https://api-m.sandbox.paypal.com/v2/checkout/orders/${orderId}/capture`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
        }
      });
      const captureData = await captureResponse.json();
      if (captureData.status === 'COMPLETED') {
        return res.json({ success: true, verified: true });
      }
    }
    res.status(400).json({ error: 'Signature verification failed' });
  } catch (error) {
    console.error('Verification error:', error);
    res.status(500).json({ error: error.message });
  }
});

app.listen(port, () => {
  console.log(`Server running on port ${port}`);
});
